[package]
name = "wide_libretro"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7.3"
log = "0.4"
once_cell = "1.10.0"
parking_lot = "0.12.0"
pretty_env_logger = "0.4"

[lib]
crate-type = ["cdylib"]
